// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
  );
  static const String _iosApiKey = String.fromEnvironment(
    'FIREBASE_IOS_API_KEY',
  );

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get android {
    if (_androidApiKey.isEmpty) {
      throw UnsupportedError(
        'Missing FIREBASE_ANDROID_API_KEY. Run with --dart-define=FIREBASE_ANDROID_API_KEY=...',
      );
    }
    return FirebaseOptions(
      apiKey: _androidApiKey,
      appId: '1:760682592524:android:581960497f24b10dfd3129',
      messagingSenderId: '760682592524',
      projectId: 'cach-reward',
      storageBucket: 'cach-reward.firebasestorage.app',
    );
  }

  static FirebaseOptions get ios {
    if (_iosApiKey.isEmpty) {
      throw UnsupportedError(
        'Missing FIREBASE_IOS_API_KEY. Run with --dart-define=FIREBASE_IOS_API_KEY=...',
      );
    }
    return FirebaseOptions(
      apiKey: _iosApiKey,
      appId: '1:760682592524:ios:2bef8de9c777f0c2fd3129',
      messagingSenderId: '760682592524',
      projectId: 'cach-reward',
      storageBucket: 'cach-reward.firebasestorage.app',
      iosClientId:
          '760682592524-ckooulhtgc0e8dr9t5dkmd7155atjjqi.apps.googleusercontent.com',
      iosBundleId: 'com.example.app',
    );
  }
}
